vim.pack.add({'https://github.com/nvim-mini/mini.nvim'})

require('mini.cursorword').setup()
require('mini.ai').setup()
require('mini.comment').setup()
require('mini.indentscope').setup()
require('mini.notify').setup()
require('mini.surround').setup()
require('mini.icons').setup()
require('mini.operators').setup()
MiniIcons.mock_nvim_web_devicons()
